blank_issues_enabled: true
contact_links:
  - name: 💬 Discord / Telegram
    url: https://t.me/aikeigroup
    about: Tanya-tanya atau diskusi ringan lewat Telegram
  - name: 📖 Dokumentasi WA-AKG
    url: https://github.com/mrifqidaffaaditya/WA-AKG/wiki
    about: Baca dokumentasi sebelum buka issue
